### ISSUE TITLE
Missing octave signs & time signatures with certain scores

### ISSUE THREAD

**Issue by captainkats** [mlang/freedots#5]
When transcribing from visual scores created with photoscore or smartscore pro from scanned printed pages, then exported to MusicXML, edited using Musescore 2.0.2 on Linux Mint 18.3 (with Ubuntu 16.04 as a base) or 2.1 on WIndows XP (special noSSE version) and exported again to musicXML, some octave signs are missing and time signature changes don't get transcribed.
Tried uploading the score to my musescore profile and downloading it as MusicXML (I thought an incompatibility issue), no change.
When downloading others' musicXML scores from MuseScore.com community, I have no issues & transcription seems to work fine.

Score is uploaded on the following page:
https://musescore.com/user/100743/scores/4942830

The score is solfege exercises & plan to use it as a helper for teenagers with sight issues on a music junior high school in Greece, after this issue gets fixed.

**Comment by mlang** [comment]
Not a bug, user did not fully understand the octave sign placement rules.
