### ISSUE TITLE
Freedots Not Compiling on Mac

### ISSUE THREAD

**Issue by judithhinlung** [mlang/freedots#8]
Running $ java -jar freedots.jar returns the error  "Unable to access file freedots.jar".  Same error when running this command in freedots/src/freedots.  
Running $ java Main.java returns a number of errors because sub-packages within the freedots package are not recognized:
Main.java:39: error: package freedots.gui does not exist
import freedots.gui.GraphicalUserInterface;
                   ^
Main.java:40: error: package freedots.musicxml does not exist
import freedots.musicxml.MIDISequence;
                        ^
Main.java:41: error: package freedots.musicxml does not exist
import freedots.musicxml.Score;
                        ^
Main.java:42: error: package freedots.playback does not exist
import freedots.playback.MIDIPlayer;
...
Will try to tackle this bug, but any help/suggestions would be most welcome :)

**Comment by mlang** [comment]
Judith Lung <notifications@github.com> writes:

> Running $ java -jar freedots.jar returns the error "Unable to access file
> freedots.jar". Same error when running this command in
> freedots/src/freedots.

You need to build freedots.jar first with "ant build".

> Running $ java Main.java returns a number of errors because sub-packages
> within the freedots package are not recognized:

Yeah, no surprise.  FreeDots is built using "ant", the standard java
build tool.

-- 
CYa,
  ⡍⠁⠗⠊⠕

**Comment by judithhinlung** [comment]
Thanks so much @Mlang for your help. I am not seeing a freedots.jar file in the repo. what commands do I need to run to build it?

**Comment by judithhinlung** [comment]
Thanks @Mlang I understand what you mean now about building a .jar file with mlang (please disregard previous comment).  For anyone else not familiar with using the Ant tool to compile an .jar file this may be a helpful read:
https://www.tutorialspoint.com/ant/ant_creating_jar_files.htm

**Comment by judithhinlung** [comment]
To build Freedots:
$ cd freedots
$ ant 
$ cd dist
$ mv freedots-[todaysDate].jar freedots.jar
$ java -jar freedots.jar

Hope this helps someone who may have trouble building the project!
